version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: url_shortener_db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: url_shortener_backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mysql


volumes:
  db_data:
